#!/usr/bin/bash

echo "Hello from create_tb"
echo "Creating table in database: $DB_NAME"

while true
do
    echo "Enter new table name:"
    read table_name
    case $table_name in
    # Empty table name
    "")
        echo "Table name cannot be empty"
        continue
        ;;
    # Table name contain space
    *" "*)
        echo "Table name cannot contain space"
        continue
        ;;
    # Table name contain special characters
    *[^a-zA-Z0-9]*)
        echo "Table name cannot contain special characters"
        continue
        ;;
    #Start with number
    [0-9]*)
        echo "Table name cannot start with number"
        continue
        ;;
    # Table name already exist
    *)
        if [ -f "/home/nadaabutaleb/ITI/Bash/Project/DB-result/$DB_NAME/$table_name" ];
        then
            echo "Table name already exist"
            continue
        else
            touch "/home/nadaabutaleb/ITI/Bash/Project/DB-result/$DB_NAME/$table_name"
            echo "Table created successfully"
            break
        fi
        ;;
    esac
done


