#!/usr/bin/bash
echo "------------------ Main Menu ------------------"
select choice in "Create DB" "List Databases" "Connect to Databases" "Drop DB" "Exit"
do
case $choice in
"Create DB")
	echo "Creating database.."
	~/ITI/Bash/Project/Code/Databases/create_db
	

	;;
"List Databases")
	echo "Listing database.."
	~/ITI/Bash/Project/Code/Databases/list_db.sh
	
	;;
"Connect to Databases")
	echo "Connecting to database.."
	~/ITI/Bash/Project/Code/Databases/connect_db.sh
	
	;;
"Drop DB")	
	echo "Drop database..:"
	~/ITI/Bash/Project/Code/Databases/drop_db.sh
	;;
"Exit")
	echo "Exit.."
	break
	;;
esac
done
