#!/usr/bin/bash

select choice in "Create DB" "List Databases" "Connect to Databases" "Drop DB" "Exit"
do
case $choice in
"Create DB")
	echo "Creating database.."
	./Databases/create_db
	;;
"List Databases")
	echo "Listing database.."
	./Databases/list_db.sh
	;;
"Connect to Databases")
	echo "Connecting to database.."
	./Databases/connect_db.sh
	;;
"Drop DB")	
	echo "Drop database..:"
	./Databases/drop_db.sh
	;;
"Exit")
	echo "Exit.."
	break
	;;
esac
done
